# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 
email: manoj220@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Welcome to my first website.Thank you! 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://manojmutagi.com" # the base hostname & protocol for your site
twitter_username: no official twitter handle
github_username:  manojmutagi

# Build settings
markdown: kramdown
